AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  dynamodbcreatetable:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: nodejs6.10
      Description: ''
      MemorySize: 128
      Timeout: 3
      Role: 'arn:aws:iam::815621908682:role/dynamodb-demo-full-access'
